config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:edit, :update, :show]
  resources :posts do
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImagesUploader
  belongs_to :user
  has_many :comments

  def self.search(search)
    return Post.all unless search
    Post.where('text LIKE(?)', "%#{search}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, uniqueness: true
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?


  private 
  def after_sign_in_path_for(resource)
    posts_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    comment = Comment.create(comment_params)
    redirect_to "/posts/#{comment.post.id}"
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.order("created_at DESC")
  end

  def new
    @post = Post.new
  end

  def create
    Post.create(post_params)
    redirect_to posts_path
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    post.update(post_params)
    redirect_to posts_path
  end

  def search
    @posts = Post.search(params[:keyword])
  end

  private
  def post_params
    params.require(:post).permit(:image, :text).merge(user_id: current_user.id)
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @name = current_user.name
    @posts = current_user.posts.order("created_at DESC")
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to posts_path
    else
      render :edit
    end
  end
  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Orthopics
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/posts/_header.html.haml
.header
  = link_to "orthopics", root_path, class: "header__logo"
  .header__search-box
    = form_with url: search_posts_path, local: true, method: :get, class: "search-form" do |form|
      = form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input"
      = form.submit "検索", class: "search-btn"
  %ul
    - if user_signed_in?
      %li
        = link_to current_user.name, user_path(current_user.id), class: "header__btn"
      %li
        = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "header__btn"
      %li
        = link_to "投稿する", new_post_path, class: "header__btn"
    - else
      %li
        = link_to "サインイン", new_user_session_path, class: "header__btn"
      %li
        = link_to "サインアップ", new_user_registration_path, class: "header__btn"

app/views/posts/_main_container.html.haml
.contents-list
  
  .contents-list__post-box
    - @posts.each do |post|
      .contents-list__post-box__new-post
        = link_to image_tag(post.image.url, class: "contents-list__post-box__new-post__image"), post_path(post.id)

app/views/posts/destroy.html.haml
%h3 削除が完了しました。
= link_to "投稿一覧へ戻る", posts_path

app/views/posts/edit.html.haml
= render "header"
.form-container
  .form-container__post-form
    %h2 編集する
    = form_with model: @post, local: true do |form|
      =form.label :image, class: "image-form" do
        = icon('fas', 'camera')
        %h3 選択
        = form.file_field :image, class: "image-icon"
      .text-form
        = form.text_area :text, class: "text-box"
        = form.submit "投稿する", class: "send-btn"

app/views/posts/index.html.haml
.wrapper
  = render "header"
  = render "main_container"

app/views/posts/new.html.haml
= render "header"
.form-container
  .form-container__post-form
    %h2 新規投稿
    = form_with model: @post, local: true do |form|
      =form.label :image, class: "image-form" do
        = icon('fas', 'camera')
        %h3 選択
        = form.file_field :image, class: "image-icon"
      .text-form
        = form.text_area :text, class: "text-box"
        = form.submit "投稿する", class: "send-btn"

app/views/posts/search.html.haml
= render "header"
.contents-list
  .contents-list__post-box
    - @posts.each do |post|
      .contents-list__post-box__new-post
        = link_to image_tag(post.image.url, class: "contents-list__post-box__new-post__image"), post_path(post.id)
        .contents-list__post-box__new-post__text
          = post.text

app/views/posts/show.html.haml
= render "header"
.main-wrapper
  = link_to posts_path, class: "back-btn" do
    = icon('fas', 'angle-double-left')
    %h1 戻る
  .main-wrapper__post-detail
    .main-wrapper__post-detail__image
      = image_tag(@post.image.url, class: "photo")
    .main-wrapper__post-detail__text-box
      = link_to @post.user.name, "/users/#{@post.user_id}", class: "post-user-name"
      = simple_format(@post.text, class: "main-wrapper__post-detail__text-box__text")
      .main-wrapper__post-detail__text-box__time
        = @post.created_at
      - if user_signed_in? && current_user.id == @post.user_id
        = link_to "編集する", "/posts/#{@post.id}/edit", method: :get, class: "main-wrapper__post-detail__update"
        = link_to "削除する", "/posts/#{@post.id}", method: :delete, class: "main-wrapper__post-detail__destroy"
      .main-wrapper__post-detail__text-box__comment-box
        %h1 【コメント】
        .main-wrapper__post-detail__text-box__comment-box__list
          - if @comments
            - @comments.each do |comment|
              = link_to comment.user.name, "/users/#{comment.user_id}", class: "user-name"
              = comment.text
        .main-wrapper__post-detail__text-box__comment-form
          = form_with model: [@post, @comment], class: "form", local: true do |form|
            = form.text_area :text, placeholder: "コメントする", class: "input-box", row: "2"
            = form.submit "送信", class: "send-btn"

app/views/posts/update.html.haml
= render "header"
%h3 更新が完了しました。
= link_to "投稿一覧へ戻る", root_path

app/views/top/index.html.haml
= render "posts/header"

.top-content
  .top-content__main-container
    %h1 orthopics
    %p 歯科矯正専用のSNS
    - if user_signed_in?
      = link_to "投稿する", new_post_path, class: "post-btn"
      = link_to "投稿をみる", posts_path, class: "post-btn"
    - else
      = link_to "サインイン", new_user_session_path, class: "post-btn"
      = link_to "投稿をみる", new_user_registration_path, class: "post-btn"

app/views/users/edit.html.haml
= render "posts/header"
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", '#', class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'

app/views/users/show.html.haml
= render "posts/header"

.contents-list
  .user-name
  = "#{@name}さんの投稿一覧"
  .contents-list__post-box
    - @posts.each do |post|
      .contents-list__post-box__new-post
        = link_to image_tag(post.image.url, class: "contents-list__post-box__new-post__image"), post_path(post.id)
        .contents-list__post-box__new-post__text
          = post.text